### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by kjkent** [kjkent/lokl-backend#6]

**Comment by PuiYanLeung** [comment]
Backend implemented authentication with JWToken, now register and login can work. However, some outstanding issues need to follow up
1. Register function involves username and password only. Change username to unique field. Also, amend email to non-mandatory field.
2. Webserver return all the fields of user including pwdHash [which is not a good practice].

**Comment by PuiYanLeung** [comment]
Backend: implemented authentication with JWToken in user and post functions.  Fixed the issue returning pwdHash.
